"""Update User table with security question and answer

Revision ID: 25f8de73d347
Revises: 3e77041af08c
Create Date: 2024-08-16 15:42:07.147991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f8de73d347'
down_revision = '3e77041af08c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=256), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
