"""Initial migration

Revision ID: 5bd80298cb84
Revises: 
Create Date: 2024-08-23 14:00:05.130501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bd80298cb84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_shelf_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='fk_book_id'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelf.id'], name='fk_shelf_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_book_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_database', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('user_database')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=256), nullable=False))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', mysql.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('publication_date',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True)

    op.create_table('user_database',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('db_list', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_database', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.drop_table('user_book')
    op.drop_table('shelf')
    # ### end Alembic commands ###
